### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by AzukayFR** [rennokki/league-api#9]
Hello man ! I have download your api today and i think about that's work but i really don't know how to use it. 

When i use the command composer require the folder comes in vendor\ so i don't have any file in the laravel project, i don't know how to configure the API_KEY and as well, i don't know how to show what i want with datadragon. 

My project : i make a website for help build and something else, and i want to show item img, title and description in the pages for all champs.. So can you help me ?? =D

Sorry for my english

**Comment by rennokki** [comment]
Hey @AzukayFR, sorry for the wait.

Basically, Composer is a tool that helps you install packages with a minimum of configuration from your side. You will have a `vendor` folder within your project and all you have to do is to go to your `.php` file and require the `vendor/autoload.php`.
